# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

profiles:
- dnsName: lb-cert.isaack.io
  lb:
    project: pytorch-tpu-nfs
    location: us-central1
    name: loadbal-cert-target-proxy-2
  issuingCa:
    project: pytorch-tpu-nfs
    location: us-central1
    name: isaack-io
  lifetimeDays: 30
  rotationThreshold: 0.9999
# - dnsName: us-central1.joonix.net
#   lb:
#     project: pytorch-tpu-nfs
#     location: us-central1
#     name: regional-test-lb-target-proxy
#   issuingCa:
#     project: pytorch-tpu-nfs
#     location: us-central1
#     name: server-tls-2
#   lifetimeDays: 30
#   rotationThreshold: 0.9999
