profiles:
- dnsName: example.com
  lb:
    project: foo
    location: global
    name: my-ssl-lb-target-proxy
  issuingCa:
    project: foo
    location: us-west1
    name: server-tls-2
  lifetimeDays: 30
  rotationThreshold: 0.9999
- dnsName: us-central1.joonix.net
  lb:
    project: foo
    location: us-central1
    name: regional-test-lb-target-proxy
  issuingCa:
    project: foo
    location: us-west1
    name: server-tls-2
  lifetimeDays: 30
  rotationThreshold: 0.9999
